2024-12-22 21:51:50,057 | ERROR | Ошибка
Traceback (most recent call last):
  File "C:\Users\Егорка\PyCharmSchool\pythonProject\Study\module_12\module_12_logg\module_12_4.py", line 27, in test_run
    r2 = rt.Runner(19,15)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Егорка\PyCharmSchool\pythonProject\Study\module_12\module_12_logg\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-22 21:51:50,058 | WARNING | Неверный тип данных для объекта Runner
2024-12-22 21:51:50,058 | INFO | "test_run" выполнен успешно
2024-12-22 21:51:50,059 | ERROR | Ошибка
Traceback (most recent call last):
  File "C:\Users\Егорка\PyCharmSchool\pythonProject\Study\module_12\module_12_logg\module_12_4.py", line 15, in test_walk
    r1 = rt.Runner('Name', -10)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Егорка\PyCharmSchool\pythonProject\Study\module_12\module_12_logg\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
2024-12-22 21:51:50,059 | WARNING | Неверная скорость для Runner
2024-12-22 21:51:50,059 | INFO | "test_walk" выполнен успешно
